# docker-compose.dev.yml
#version: '3'

networks:
  blinko-network:
    driver: bridge

services:
  blinko-website:
    container_name: blinko-website
    build:
      context: .
      args:
        USE_MIRROR: "true"  
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:1111
      NEXT_PUBLIC_BASE_URL: http://localhost:1111
      NEXTAUTH_SECRET: Bhtcgroup.0
      DATABASE_URL: postgresql://postgres:Bhtcgroup.0@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 1111:1111
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://blinko-website:1111/"]
      interval: 30s 
      timeout: 10s  
      retries: 5
      start_period: 30s
    networks:
      - blinko-network

  postgres:
    image: swr.cn-north-4.myhuaweicloud.com/library/postgres:14-alpine
    container_name: blinko-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bhtcgroup.0
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
