# docker-compose.dev.yml
# version: '3'

networks:
  blinko-network:
    driver: bridge

services:
  blinko-website:
    image: ambersvision/geoblinko:latest
    container_name: Geoblinko-website
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:2222
      NEXT_PUBLIC_BASE_URL: http://localhost:2222
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your_nextauth_secret_here}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-your_password_here}@postgres:5432/postgres
      AMAP_WEB_API_KEY: ${AMAP_WEB_API_KEY:-your_amap_api_key_here}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 2222:1111
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://blinko-website:2222/"]
      interval: 30s 
      timeout: 10s  
      retries: 5
      start_period: 30s
    networks:
      - blinko-network

  postgres:
    image: postgres:latest
    container_name: Geoblinko-postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password_here}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
